platform :ios, 9.0
#use_frameworks!

target 'YouChainWallet' do


    rn_path = '../node_modules/react-native'

    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTCameraRoll',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTPushNotification'
    ]

    pod 'CodePush', :path => '../node_modules/react-native-code-push'
    pod 'RNI18n', :path => '../node_modules/react-native-i18n'
    pod 'Picker', :path => '../node_modules/react-native-picker'
    pod 'RNFS', :path => '../node_modules/react-native-fs'
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'
    pod 'SVProgressHUD'

    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  	pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  	pod 'GoogleMobileVision/FaceDetector'
  	pod 'GoogleMobileVision/MVDataOutput'

  	pod 'RNSound', :path => '../node_modules/react-native-sound'

	pod 'mob_sharesdk' , '4.1.1'

	# UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
	pod 'mob_sharesdk/ShareSDKUI'

	# 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
	pod 'mob_sharesdk/ShareSDKPlatforms/Facebook'
	pod 'mob_sharesdk/ShareSDKPlatforms/Twitter'
#	pod 'mob_sharesdk/ShareSDKPlatforms/Line'
	pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'
	pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
	pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
	pod 'mob_sharesdk/ShareSDKPlatforms/Copy'

	# 使用配置文件分享模块（非必需）
#	pod 'mob_sharesdk/ShareSDKConfigurationFile'

	# 扩展模块（在调用可以弹出我们UI分享方法的时候是必需的）
	pod 'mob_sharesdk/ShareSDKExtension'

  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'
#  pod 'PgyUpdate'

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'React', :path => '../node_modules/react-native'
  
  pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'react-native-google-maps'
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
        if target.name == "React"
            target.remove_from_project
        end
    end
end
